version: '3.8'

services:
  web:
    image: ghcr.io/adrianoferraz01/django-agrohub:latest
    networks:
      - traefik-proxy
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.django-hello-world.rule=Host(`meusite.com`)"
        - "traefik.http.routers.django-hello-world.entrypoints=web"
        - "traefik.http.services.django-hello-world.loadbalancer.server.port=8000"
        - "traefik.docker.network=traefik-proxy"

networks:
  traefik-proxy:
    external: true
    name: traefik-proxy # Nome da rede do Traefik local
