version: '3.8'

services:
  web:
    build: .
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    build: ./nginx
    ports:
      - "87:87"
    depends_on:
      - web
    deploy:
      restart_policy:
        condition: on-failure
